### PR TITLE
Add TypeScript as a supported type

### PR DESCRIPTION
**Pull request by brettcannon**

### CODE REVIEW

**Comment by asottile** [comment]
this file is generated, please edit the github action instead

also `types` is evaluated with `AND` and so your change would cause it to match nothing, you probably want `types_or` which is brand new (needs `minimum_pre_commit_version` set as well)

**Comment by brettcannon** [comment]
Found https://github.com/pre-commit/pre-commit/blob/master/CHANGELOG.md#290---2020-11-21 which means 2.9.0 is the minimum version to support.

@asottile I opened https://github.com/pre-commit/pre-commit-mirror-maker/issues/69 as pre-commit-mirror-maker doesn't look to support `types_or` yet.

**Comment by flying-sheep** [comment]
Can you please merge this?

**Comment by asottile** [comment]
@flying-sheep no, please read https://github.com/pre-commit/mirrors-eslint/pull/26#issuecomment-750934577

**Pull request closed without merging**
